name: Emit Actual Sustainability Metrics

on: [push]

jobs:
  collect-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Scaphandre
        run: |
          # Get latest version
          VERSION=$(curl -s https://api.github.com/repos/hubblo-org/scaphandre/releases/latest | grep tag_name | cut -d '"' -f 4)
          
          # Download and extract
          wget https://github.com/hubblo-org/scaphandre/releases/download/${VERSION}/scaphandre_x86_64-unknown-linux-gnu.tar.gz
          tar -xzf scaphandre_x86_64-unknown-linux-gnu.tar.gz
          sudo mv scaphandre /usr/local/bin/
          
          # Confirm installation
          scaphandre --version


      - name: Install project dependencies
        run: npm install

      - name: Measure energy usage with Scaphandre
        run: |
          sudo scaphandre json > scaphandre-output.json &
          export SCAPH_PID=$!
          npm run build
          sleep 2
          kill $SCAPH_PID

      - name: Inspect output
        run: cat scaphandre-output.json

      - name: Post to the Test API
        run: |
          curl -X POST https://webhook.site/cf18b7b0-ddad-4cc2-8a6e-fc7cdfc8f973 \
          -H "Content-Type: application/json" \
          -d @scaphandre-output.json
